name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Verify JAR file
      run: ls -l build/libs/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-artifact
        path: build/libs/*.jar

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-java

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: java-artifact
        path: ./downloaded-artifacts/

    - name: Verify downloaded artifact
      run: ls -l ./downloaded-artifacts/
